# Generated by Django 3.2.19 on 2023-06-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(default=99999942)),
                ("server_id", models.BigIntegerField(default=0, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("server_id", models.BigIntegerField(default=0, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="fakeapi.post",
                    ),
                ),
            ],
        ),
    ]
